export default {
    FETCH_BOOKS_BEGIN: 'FETCH_BOOKS_BEGIN',
    FETCH_BOOKS_SUCCESS: 'FETCH_BOOKS_SUCCESS',
    FETCH_BOOKS_FAILURE: 'FETCH_BOOKS_FAILURE',
    FETCH_BOOK_BEGIN: 'FETCH_BOOK_BEGIN',
    FETCH_BOOK_SUCCESS: 'FETCH_BOOK_SUCCESS',
    FETCH_BOOK_FAILURE: 'FETCH_BOOK_FAILURE',
    MUTATION_BEGIN: 'MUTATIONK_BEGIN',
    MUTATION_SUCCESS: 'MUTATION_SUCCESS',
    MUTATION_FAILURE: 'MUTATION_FAILURE',
    SHOW_NOTIFICATION: 'SHOW_NOTIFICATION',
    HIDE_NOTIFICATION: 'HIDE_NOTIFICATION',
};
