export default {
    FETCH_BOOKS_BEGIN: 'FETCH_BOOKS_BEGIN',
    FETCH_BOOKS_SUCCESS: 'FETCH_BOOKS_SUCCESS',
    FETCH_BOOKS_FAILURE: 'FETCH_BOOKS_FAILURE',
    PROCESS_BOOK_BEGIN: 'PROCESS_BOOK_BEGIN',
    PROCESS_BOOK_SUCCESS: 'PROCESS_BOOK_SUCCESS',
    PROCESS_BOOK_FAILURE: 'PROCESS_BOOK_FAILURE',
    SHOW_NOTIFICATION: 'SHOW_NOTIFICATION',
    HIDE_NOTIFICATION: 'HIDE_NOTIFICATION',
};
