export default {
    FETCH_BOOKS: 'FETCH_BOOKS',
    ADD_BOOK: 'ADD_BOOK',
    UPDATE_BOOK: 'UPDATE_BOOK',
    CREATE_NOTIFICATION: 'CREATE_NOTIFICATION',
    DELETE_NOTIFICATION: 'DELETE_NOTIFICATION',
};
